# Generated by Django 3.1.4 on 2020-12-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter_topic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newslettertopic",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
